package com.gm.osoa.orm.mybatis.dao;

import com.gm.osoa.orm.mybatis.model.Dept;
import com.gm.osoa.orm.mybatis.model.DeptExample;
import com.gm.osoa.orm.mybatis.model.Er;
import com.gm.osoa.orm.mybatis.model.ErExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErMapper extends BaseMapper<Er, ErExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int countByExample(ErExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int deleteByExample(ErExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int deleteByPrimaryKey(String erId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int insert(Er record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int insertSelective(Er record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    List<Er> selectByExample(ErExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    Er selectByPrimaryKey(String erId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") Er record, @Param("example") ErExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByExample(@Param("record") Er record, @Param("example") ErExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByPrimaryKeySelective(Er record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByPrimaryKey(Er record);
}