package com.gm.osoa.orm.mybatis.dao;

import com.gm.osoa.orm.mybatis.model.Privilege;
import com.gm.osoa.orm.mybatis.model.PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper extends BaseMapper<Privilege, PrivilegeExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int countByExample(PrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int deleteByExample(PrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int deleteByPrimaryKey(String priId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int insert(Privilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int insertSelective(Privilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	List<Privilege> selectByExample(PrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	Privilege selectByPrimaryKey(String priId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Privilege record,
			@Param("example") PrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int updateByExample(@Param("record") Privilege record,
			@Param("example") PrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int updateByPrimaryKeySelective(Privilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	int updateByPrimaryKey(Privilege record);
}