package com.gm.osoa.orm.mybatis.dao;

import com.gm.osoa.orm.mybatis.model.Pr;
import com.gm.osoa.orm.mybatis.model.PrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrMapper extends BaseMapper<Pr, PrExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int countByExample(PrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int deleteByExample(PrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int insert(Pr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int insertSelective(Pr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    List<Pr> selectByExample(PrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") Pr record, @Param("example") PrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    int updateByExample(@Param("record") Pr record, @Param("example") PrExample example);
}