package com.gm.osoa.orm.mybatis.model;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.springframework.format.annotation.DateTimeFormat;

import com.gm.osoa.common.JsonDateSerializer;

public class Emp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.emp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.dept_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.emp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String empCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.emp_pwd
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String empPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.emp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String empName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.emp_ep_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String empEpName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.sex
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.birthday
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.np
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String np;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.nation
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String nation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.cardtp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String cardtp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.cardno
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String cardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.eb
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String eb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.pro
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String pro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.tp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String tp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.posts
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String posts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.ploityface
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String ploityface;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.jobtel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String jobtel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.mobile
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.hometel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String hometel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.homeaddr
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String homeaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.email
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.jobst
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date jobst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.intotime
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date intotime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.contract
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String contract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.emp_id
	 * @return  the value of emp.emp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.emp_id
	 * @param empId  the value for emp.emp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmpId(String empId) {
		this.empId = empId == null ? null : empId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.dept_id
	 * @return  the value of emp.dept_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.dept_id
	 * @param deptId  the value for emp.dept_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId == null ? null : deptId.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.emp_code
	 * @return  the value of emp.emp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmpCode() {
		return empCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.emp_code
	 * @param empCode  the value for emp.emp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmpCode(String empCode) {
		this.empCode = empCode == null ? null : empCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.emp_pwd
	 * @return  the value of emp.emp_pwd
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmpPwd() {
		return empPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.emp_pwd
	 * @param empPwd  the value for emp.emp_pwd
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmpPwd(String empPwd) {
		this.empPwd = empPwd == null ? null : empPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.emp_name
	 * @return  the value of emp.emp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmpName() {
		return empName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.emp_name
	 * @param empName  the value for emp.emp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmpName(String empName) {
		this.empName = empName == null ? null : empName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.emp_ep_name
	 * @return  the value of emp.emp_ep_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmpEpName() {
		return empEpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.emp_ep_name
	 * @param empEpName  the value for emp.emp_ep_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmpEpName(String empEpName) {
		this.empEpName = empEpName == null ? null : empEpName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.sex
	 * @return  the value of emp.sex
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.sex
	 * @param sex  the value for emp.sex
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.birthday
	 * @return  the value of emp.birthday
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.birthday
	 * @param birthday  the value for emp.birthday
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.np
	 * @return  the value of emp.np
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getNp() {
		return np;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.np
	 * @param np  the value for emp.np
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setNp(String np) {
		this.np = np == null ? null : np.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.nation
	 * @return  the value of emp.nation
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.nation
	 * @param nation  the value for emp.nation
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setNation(String nation) {
		this.nation = nation == null ? null : nation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.cardtp
	 * @return  the value of emp.cardtp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getCardtp() {
		return cardtp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.cardtp
	 * @param cardtp  the value for emp.cardtp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setCardtp(String cardtp) {
		this.cardtp = cardtp == null ? null : cardtp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.cardno
	 * @return  the value of emp.cardno
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getCardno() {
		return cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.cardno
	 * @param cardno  the value for emp.cardno
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno == null ? null : cardno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.eb
	 * @return  the value of emp.eb
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEb() {
		return eb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.eb
	 * @param eb  the value for emp.eb
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEb(String eb) {
		this.eb = eb == null ? null : eb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.pro
	 * @return  the value of emp.pro
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getPro() {
		return pro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.pro
	 * @param pro  the value for emp.pro
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setPro(String pro) {
		this.pro = pro == null ? null : pro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.tp
	 * @return  the value of emp.tp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getTp() {
		return tp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.tp
	 * @param tp  the value for emp.tp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setTp(String tp) {
		this.tp = tp == null ? null : tp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.posts
	 * @return  the value of emp.posts
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getPosts() {
		return posts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.posts
	 * @param posts  the value for emp.posts
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setPosts(String posts) {
		this.posts = posts == null ? null : posts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.ploityface
	 * @return  the value of emp.ploityface
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getPloityface() {
		return ploityface;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.ploityface
	 * @param ploityface  the value for emp.ploityface
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setPloityface(String ploityface) {
		this.ploityface = ploityface == null ? null : ploityface.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.jobtel
	 * @return  the value of emp.jobtel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getJobtel() {
		return jobtel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.jobtel
	 * @param jobtel  the value for emp.jobtel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setJobtel(String jobtel) {
		this.jobtel = jobtel == null ? null : jobtel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.mobile
	 * @return  the value of emp.mobile
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.mobile
	 * @param mobile  the value for emp.mobile
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.hometel
	 * @return  the value of emp.hometel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getHometel() {
		return hometel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.hometel
	 * @param hometel  the value for emp.hometel
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setHometel(String hometel) {
		this.hometel = hometel == null ? null : hometel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.homeaddr
	 * @return  the value of emp.homeaddr
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getHomeaddr() {
		return homeaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.homeaddr
	 * @param homeaddr  the value for emp.homeaddr
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setHomeaddr(String homeaddr) {
		this.homeaddr = homeaddr == null ? null : homeaddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.email
	 * @return  the value of emp.email
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.email
	 * @param email  the value for emp.email
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.jobst
	 * @return  the value of emp.jobst
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getJobst() {
		return jobst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.jobst
	 * @param jobst  the value for emp.jobst
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setJobst(Date jobst) {
		this.jobst = jobst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.intotime
	 * @return  the value of emp.intotime
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getIntotime() {
		return intotime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.intotime
	 * @param intotime  the value for emp.intotime
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setIntotime(Date intotime) {
		this.intotime = intotime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.contract
	 * @return  the value of emp.contract
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getContract() {
		return contract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.contract
	 * @param contract  the value for emp.contract
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setContract(String contract) {
		this.contract = contract == null ? null : contract.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp.remark
	 * @return  the value of emp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp.remark
	 * @param remark  the value for emp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}