package com.gm.osoa.orm.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmpExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public EmpExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andEmpIdIsNull() {
			addCriterion("emp_id is null");
			return (Criteria) this;
		}

		public Criteria andEmpIdIsNotNull() {
			addCriterion("emp_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmpIdEqualTo(String value) {
			addCriterion("emp_id =", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotEqualTo(String value) {
			addCriterion("emp_id <>", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThan(String value) {
			addCriterion("emp_id >", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
			addCriterion("emp_id >=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThan(String value) {
			addCriterion("emp_id <", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLessThanOrEqualTo(String value) {
			addCriterion("emp_id <=", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdLike(String value) {
			addCriterion("emp_id like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotLike(String value) {
			addCriterion("emp_id not like", value, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdIn(List<String> values) {
			addCriterion("emp_id in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotIn(List<String> values) {
			addCriterion("emp_id not in", values, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdBetween(String value1, String value2) {
			addCriterion("emp_id between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andEmpIdNotBetween(String value1, String value2) {
			addCriterion("emp_id not between", value1, value2, "empId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNull() {
			addCriterion("dept_id is null");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNotNull() {
			addCriterion("dept_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeptIdEqualTo(String value) {
			addCriterion("dept_id =", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotEqualTo(String value) {
			addCriterion("dept_id <>", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThan(String value) {
			addCriterion("dept_id >", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
			addCriterion("dept_id >=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThan(String value) {
			addCriterion("dept_id <", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThanOrEqualTo(String value) {
			addCriterion("dept_id <=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLike(String value) {
			addCriterion("dept_id like", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotLike(String value) {
			addCriterion("dept_id not like", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIn(List<String> values) {
			addCriterion("dept_id in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotIn(List<String> values) {
			addCriterion("dept_id not in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdBetween(String value1, String value2) {
			addCriterion("dept_id between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotBetween(String value1, String value2) {
			addCriterion("dept_id not between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIsNull() {
			addCriterion("emp_code is null");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIsNotNull() {
			addCriterion("emp_code is not null");
			return (Criteria) this;
		}

		public Criteria andEmpCodeEqualTo(String value) {
			addCriterion("emp_code =", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotEqualTo(String value) {
			addCriterion("emp_code <>", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeGreaterThan(String value) {
			addCriterion("emp_code >", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeGreaterThanOrEqualTo(String value) {
			addCriterion("emp_code >=", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLessThan(String value) {
			addCriterion("emp_code <", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLessThanOrEqualTo(String value) {
			addCriterion("emp_code <=", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeLike(String value) {
			addCriterion("emp_code like", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotLike(String value) {
			addCriterion("emp_code not like", value, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeIn(List<String> values) {
			addCriterion("emp_code in", values, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotIn(List<String> values) {
			addCriterion("emp_code not in", values, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeBetween(String value1, String value2) {
			addCriterion("emp_code between", value1, value2, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpCodeNotBetween(String value1, String value2) {
			addCriterion("emp_code not between", value1, value2, "empCode");
			return (Criteria) this;
		}

		public Criteria andEmpPwdIsNull() {
			addCriterion("emp_pwd is null");
			return (Criteria) this;
		}

		public Criteria andEmpPwdIsNotNull() {
			addCriterion("emp_pwd is not null");
			return (Criteria) this;
		}

		public Criteria andEmpPwdEqualTo(String value) {
			addCriterion("emp_pwd =", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdNotEqualTo(String value) {
			addCriterion("emp_pwd <>", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdGreaterThan(String value) {
			addCriterion("emp_pwd >", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdGreaterThanOrEqualTo(String value) {
			addCriterion("emp_pwd >=", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdLessThan(String value) {
			addCriterion("emp_pwd <", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdLessThanOrEqualTo(String value) {
			addCriterion("emp_pwd <=", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdLike(String value) {
			addCriterion("emp_pwd like", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdNotLike(String value) {
			addCriterion("emp_pwd not like", value, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdIn(List<String> values) {
			addCriterion("emp_pwd in", values, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdNotIn(List<String> values) {
			addCriterion("emp_pwd not in", values, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdBetween(String value1, String value2) {
			addCriterion("emp_pwd between", value1, value2, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpPwdNotBetween(String value1, String value2) {
			addCriterion("emp_pwd not between", value1, value2, "empPwd");
			return (Criteria) this;
		}

		public Criteria andEmpNameIsNull() {
			addCriterion("emp_name is null");
			return (Criteria) this;
		}

		public Criteria andEmpNameIsNotNull() {
			addCriterion("emp_name is not null");
			return (Criteria) this;
		}

		public Criteria andEmpNameEqualTo(String value) {
			addCriterion("emp_name =", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotEqualTo(String value) {
			addCriterion("emp_name <>", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameGreaterThan(String value) {
			addCriterion("emp_name >", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
			addCriterion("emp_name >=", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLessThan(String value) {
			addCriterion("emp_name <", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLessThanOrEqualTo(String value) {
			addCriterion("emp_name <=", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameLike(String value) {
			addCriterion("emp_name like", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotLike(String value) {
			addCriterion("emp_name not like", value, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameIn(List<String> values) {
			addCriterion("emp_name in", values, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotIn(List<String> values) {
			addCriterion("emp_name not in", values, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameBetween(String value1, String value2) {
			addCriterion("emp_name between", value1, value2, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpNameNotBetween(String value1, String value2) {
			addCriterion("emp_name not between", value1, value2, "empName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameIsNull() {
			addCriterion("emp_ep_name is null");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameIsNotNull() {
			addCriterion("emp_ep_name is not null");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameEqualTo(String value) {
			addCriterion("emp_ep_name =", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameNotEqualTo(String value) {
			addCriterion("emp_ep_name <>", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameGreaterThan(String value) {
			addCriterion("emp_ep_name >", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameGreaterThanOrEqualTo(String value) {
			addCriterion("emp_ep_name >=", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameLessThan(String value) {
			addCriterion("emp_ep_name <", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameLessThanOrEqualTo(String value) {
			addCriterion("emp_ep_name <=", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameLike(String value) {
			addCriterion("emp_ep_name like", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameNotLike(String value) {
			addCriterion("emp_ep_name not like", value, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameIn(List<String> values) {
			addCriterion("emp_ep_name in", values, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameNotIn(List<String> values) {
			addCriterion("emp_ep_name not in", values, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameBetween(String value1, String value2) {
			addCriterion("emp_ep_name between", value1, value2, "empEpName");
			return (Criteria) this;
		}

		public Criteria andEmpEpNameNotBetween(String value1, String value2) {
			addCriterion("emp_ep_name not between", value1, value2, "empEpName");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2,
					"birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2,
					"birthday");
			return (Criteria) this;
		}

		public Criteria andNpIsNull() {
			addCriterion("np is null");
			return (Criteria) this;
		}

		public Criteria andNpIsNotNull() {
			addCriterion("np is not null");
			return (Criteria) this;
		}

		public Criteria andNpEqualTo(String value) {
			addCriterion("np =", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpNotEqualTo(String value) {
			addCriterion("np <>", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpGreaterThan(String value) {
			addCriterion("np >", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpGreaterThanOrEqualTo(String value) {
			addCriterion("np >=", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpLessThan(String value) {
			addCriterion("np <", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpLessThanOrEqualTo(String value) {
			addCriterion("np <=", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpLike(String value) {
			addCriterion("np like", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpNotLike(String value) {
			addCriterion("np not like", value, "np");
			return (Criteria) this;
		}

		public Criteria andNpIn(List<String> values) {
			addCriterion("np in", values, "np");
			return (Criteria) this;
		}

		public Criteria andNpNotIn(List<String> values) {
			addCriterion("np not in", values, "np");
			return (Criteria) this;
		}

		public Criteria andNpBetween(String value1, String value2) {
			addCriterion("np between", value1, value2, "np");
			return (Criteria) this;
		}

		public Criteria andNpNotBetween(String value1, String value2) {
			addCriterion("np not between", value1, value2, "np");
			return (Criteria) this;
		}

		public Criteria andNationIsNull() {
			addCriterion("nation is null");
			return (Criteria) this;
		}

		public Criteria andNationIsNotNull() {
			addCriterion("nation is not null");
			return (Criteria) this;
		}

		public Criteria andNationEqualTo(String value) {
			addCriterion("nation =", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationNotEqualTo(String value) {
			addCriterion("nation <>", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationGreaterThan(String value) {
			addCriterion("nation >", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationGreaterThanOrEqualTo(String value) {
			addCriterion("nation >=", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationLessThan(String value) {
			addCriterion("nation <", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationLessThanOrEqualTo(String value) {
			addCriterion("nation <=", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationLike(String value) {
			addCriterion("nation like", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationNotLike(String value) {
			addCriterion("nation not like", value, "nation");
			return (Criteria) this;
		}

		public Criteria andNationIn(List<String> values) {
			addCriterion("nation in", values, "nation");
			return (Criteria) this;
		}

		public Criteria andNationNotIn(List<String> values) {
			addCriterion("nation not in", values, "nation");
			return (Criteria) this;
		}

		public Criteria andNationBetween(String value1, String value2) {
			addCriterion("nation between", value1, value2, "nation");
			return (Criteria) this;
		}

		public Criteria andNationNotBetween(String value1, String value2) {
			addCriterion("nation not between", value1, value2, "nation");
			return (Criteria) this;
		}

		public Criteria andCardtpIsNull() {
			addCriterion("cardtp is null");
			return (Criteria) this;
		}

		public Criteria andCardtpIsNotNull() {
			addCriterion("cardtp is not null");
			return (Criteria) this;
		}

		public Criteria andCardtpEqualTo(String value) {
			addCriterion("cardtp =", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpNotEqualTo(String value) {
			addCriterion("cardtp <>", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpGreaterThan(String value) {
			addCriterion("cardtp >", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpGreaterThanOrEqualTo(String value) {
			addCriterion("cardtp >=", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpLessThan(String value) {
			addCriterion("cardtp <", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpLessThanOrEqualTo(String value) {
			addCriterion("cardtp <=", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpLike(String value) {
			addCriterion("cardtp like", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpNotLike(String value) {
			addCriterion("cardtp not like", value, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpIn(List<String> values) {
			addCriterion("cardtp in", values, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpNotIn(List<String> values) {
			addCriterion("cardtp not in", values, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpBetween(String value1, String value2) {
			addCriterion("cardtp between", value1, value2, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardtpNotBetween(String value1, String value2) {
			addCriterion("cardtp not between", value1, value2, "cardtp");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNull() {
			addCriterion("cardno is null");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNotNull() {
			addCriterion("cardno is not null");
			return (Criteria) this;
		}

		public Criteria andCardnoEqualTo(String value) {
			addCriterion("cardno =", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotEqualTo(String value) {
			addCriterion("cardno <>", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThan(String value) {
			addCriterion("cardno >", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThanOrEqualTo(String value) {
			addCriterion("cardno >=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThan(String value) {
			addCriterion("cardno <", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThanOrEqualTo(String value) {
			addCriterion("cardno <=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLike(String value) {
			addCriterion("cardno like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotLike(String value) {
			addCriterion("cardno not like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoIn(List<String> values) {
			addCriterion("cardno in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotIn(List<String> values) {
			addCriterion("cardno not in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoBetween(String value1, String value2) {
			addCriterion("cardno between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotBetween(String value1, String value2) {
			addCriterion("cardno not between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andEbIsNull() {
			addCriterion("eb is null");
			return (Criteria) this;
		}

		public Criteria andEbIsNotNull() {
			addCriterion("eb is not null");
			return (Criteria) this;
		}

		public Criteria andEbEqualTo(String value) {
			addCriterion("eb =", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbNotEqualTo(String value) {
			addCriterion("eb <>", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbGreaterThan(String value) {
			addCriterion("eb >", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbGreaterThanOrEqualTo(String value) {
			addCriterion("eb >=", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbLessThan(String value) {
			addCriterion("eb <", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbLessThanOrEqualTo(String value) {
			addCriterion("eb <=", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbLike(String value) {
			addCriterion("eb like", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbNotLike(String value) {
			addCriterion("eb not like", value, "eb");
			return (Criteria) this;
		}

		public Criteria andEbIn(List<String> values) {
			addCriterion("eb in", values, "eb");
			return (Criteria) this;
		}

		public Criteria andEbNotIn(List<String> values) {
			addCriterion("eb not in", values, "eb");
			return (Criteria) this;
		}

		public Criteria andEbBetween(String value1, String value2) {
			addCriterion("eb between", value1, value2, "eb");
			return (Criteria) this;
		}

		public Criteria andEbNotBetween(String value1, String value2) {
			addCriterion("eb not between", value1, value2, "eb");
			return (Criteria) this;
		}

		public Criteria andProIsNull() {
			addCriterion("pro is null");
			return (Criteria) this;
		}

		public Criteria andProIsNotNull() {
			addCriterion("pro is not null");
			return (Criteria) this;
		}

		public Criteria andProEqualTo(String value) {
			addCriterion("pro =", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProNotEqualTo(String value) {
			addCriterion("pro <>", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProGreaterThan(String value) {
			addCriterion("pro >", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProGreaterThanOrEqualTo(String value) {
			addCriterion("pro >=", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProLessThan(String value) {
			addCriterion("pro <", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProLessThanOrEqualTo(String value) {
			addCriterion("pro <=", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProLike(String value) {
			addCriterion("pro like", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProNotLike(String value) {
			addCriterion("pro not like", value, "pro");
			return (Criteria) this;
		}

		public Criteria andProIn(List<String> values) {
			addCriterion("pro in", values, "pro");
			return (Criteria) this;
		}

		public Criteria andProNotIn(List<String> values) {
			addCriterion("pro not in", values, "pro");
			return (Criteria) this;
		}

		public Criteria andProBetween(String value1, String value2) {
			addCriterion("pro between", value1, value2, "pro");
			return (Criteria) this;
		}

		public Criteria andProNotBetween(String value1, String value2) {
			addCriterion("pro not between", value1, value2, "pro");
			return (Criteria) this;
		}

		public Criteria andTpIsNull() {
			addCriterion("tp is null");
			return (Criteria) this;
		}

		public Criteria andTpIsNotNull() {
			addCriterion("tp is not null");
			return (Criteria) this;
		}

		public Criteria andTpEqualTo(String value) {
			addCriterion("tp =", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpNotEqualTo(String value) {
			addCriterion("tp <>", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpGreaterThan(String value) {
			addCriterion("tp >", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpGreaterThanOrEqualTo(String value) {
			addCriterion("tp >=", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpLessThan(String value) {
			addCriterion("tp <", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpLessThanOrEqualTo(String value) {
			addCriterion("tp <=", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpLike(String value) {
			addCriterion("tp like", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpNotLike(String value) {
			addCriterion("tp not like", value, "tp");
			return (Criteria) this;
		}

		public Criteria andTpIn(List<String> values) {
			addCriterion("tp in", values, "tp");
			return (Criteria) this;
		}

		public Criteria andTpNotIn(List<String> values) {
			addCriterion("tp not in", values, "tp");
			return (Criteria) this;
		}

		public Criteria andTpBetween(String value1, String value2) {
			addCriterion("tp between", value1, value2, "tp");
			return (Criteria) this;
		}

		public Criteria andTpNotBetween(String value1, String value2) {
			addCriterion("tp not between", value1, value2, "tp");
			return (Criteria) this;
		}

		public Criteria andPostsIsNull() {
			addCriterion("posts is null");
			return (Criteria) this;
		}

		public Criteria andPostsIsNotNull() {
			addCriterion("posts is not null");
			return (Criteria) this;
		}

		public Criteria andPostsEqualTo(String value) {
			addCriterion("posts =", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsNotEqualTo(String value) {
			addCriterion("posts <>", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsGreaterThan(String value) {
			addCriterion("posts >", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsGreaterThanOrEqualTo(String value) {
			addCriterion("posts >=", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsLessThan(String value) {
			addCriterion("posts <", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsLessThanOrEqualTo(String value) {
			addCriterion("posts <=", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsLike(String value) {
			addCriterion("posts like", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsNotLike(String value) {
			addCriterion("posts not like", value, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsIn(List<String> values) {
			addCriterion("posts in", values, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsNotIn(List<String> values) {
			addCriterion("posts not in", values, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsBetween(String value1, String value2) {
			addCriterion("posts between", value1, value2, "posts");
			return (Criteria) this;
		}

		public Criteria andPostsNotBetween(String value1, String value2) {
			addCriterion("posts not between", value1, value2, "posts");
			return (Criteria) this;
		}

		public Criteria andPloityfaceIsNull() {
			addCriterion("ploityface is null");
			return (Criteria) this;
		}

		public Criteria andPloityfaceIsNotNull() {
			addCriterion("ploityface is not null");
			return (Criteria) this;
		}

		public Criteria andPloityfaceEqualTo(String value) {
			addCriterion("ploityface =", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceNotEqualTo(String value) {
			addCriterion("ploityface <>", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceGreaterThan(String value) {
			addCriterion("ploityface >", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceGreaterThanOrEqualTo(String value) {
			addCriterion("ploityface >=", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceLessThan(String value) {
			addCriterion("ploityface <", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceLessThanOrEqualTo(String value) {
			addCriterion("ploityface <=", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceLike(String value) {
			addCriterion("ploityface like", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceNotLike(String value) {
			addCriterion("ploityface not like", value, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceIn(List<String> values) {
			addCriterion("ploityface in", values, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceNotIn(List<String> values) {
			addCriterion("ploityface not in", values, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceBetween(String value1, String value2) {
			addCriterion("ploityface between", value1, value2, "ploityface");
			return (Criteria) this;
		}

		public Criteria andPloityfaceNotBetween(String value1, String value2) {
			addCriterion("ploityface not between", value1, value2, "ploityface");
			return (Criteria) this;
		}

		public Criteria andJobtelIsNull() {
			addCriterion("jobtel is null");
			return (Criteria) this;
		}

		public Criteria andJobtelIsNotNull() {
			addCriterion("jobtel is not null");
			return (Criteria) this;
		}

		public Criteria andJobtelEqualTo(String value) {
			addCriterion("jobtel =", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelNotEqualTo(String value) {
			addCriterion("jobtel <>", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelGreaterThan(String value) {
			addCriterion("jobtel >", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelGreaterThanOrEqualTo(String value) {
			addCriterion("jobtel >=", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelLessThan(String value) {
			addCriterion("jobtel <", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelLessThanOrEqualTo(String value) {
			addCriterion("jobtel <=", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelLike(String value) {
			addCriterion("jobtel like", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelNotLike(String value) {
			addCriterion("jobtel not like", value, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelIn(List<String> values) {
			addCriterion("jobtel in", values, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelNotIn(List<String> values) {
			addCriterion("jobtel not in", values, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelBetween(String value1, String value2) {
			addCriterion("jobtel between", value1, value2, "jobtel");
			return (Criteria) this;
		}

		public Criteria andJobtelNotBetween(String value1, String value2) {
			addCriterion("jobtel not between", value1, value2, "jobtel");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andHometelIsNull() {
			addCriterion("hometel is null");
			return (Criteria) this;
		}

		public Criteria andHometelIsNotNull() {
			addCriterion("hometel is not null");
			return (Criteria) this;
		}

		public Criteria andHometelEqualTo(String value) {
			addCriterion("hometel =", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelNotEqualTo(String value) {
			addCriterion("hometel <>", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelGreaterThan(String value) {
			addCriterion("hometel >", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelGreaterThanOrEqualTo(String value) {
			addCriterion("hometel >=", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelLessThan(String value) {
			addCriterion("hometel <", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelLessThanOrEqualTo(String value) {
			addCriterion("hometel <=", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelLike(String value) {
			addCriterion("hometel like", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelNotLike(String value) {
			addCriterion("hometel not like", value, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelIn(List<String> values) {
			addCriterion("hometel in", values, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelNotIn(List<String> values) {
			addCriterion("hometel not in", values, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelBetween(String value1, String value2) {
			addCriterion("hometel between", value1, value2, "hometel");
			return (Criteria) this;
		}

		public Criteria andHometelNotBetween(String value1, String value2) {
			addCriterion("hometel not between", value1, value2, "hometel");
			return (Criteria) this;
		}

		public Criteria andHomeaddrIsNull() {
			addCriterion("homeaddr is null");
			return (Criteria) this;
		}

		public Criteria andHomeaddrIsNotNull() {
			addCriterion("homeaddr is not null");
			return (Criteria) this;
		}

		public Criteria andHomeaddrEqualTo(String value) {
			addCriterion("homeaddr =", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrNotEqualTo(String value) {
			addCriterion("homeaddr <>", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrGreaterThan(String value) {
			addCriterion("homeaddr >", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrGreaterThanOrEqualTo(String value) {
			addCriterion("homeaddr >=", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrLessThan(String value) {
			addCriterion("homeaddr <", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrLessThanOrEqualTo(String value) {
			addCriterion("homeaddr <=", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrLike(String value) {
			addCriterion("homeaddr like", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrNotLike(String value) {
			addCriterion("homeaddr not like", value, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrIn(List<String> values) {
			addCriterion("homeaddr in", values, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrNotIn(List<String> values) {
			addCriterion("homeaddr not in", values, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrBetween(String value1, String value2) {
			addCriterion("homeaddr between", value1, value2, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andHomeaddrNotBetween(String value1, String value2) {
			addCriterion("homeaddr not between", value1, value2, "homeaddr");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andJobstIsNull() {
			addCriterion("jobst is null");
			return (Criteria) this;
		}

		public Criteria andJobstIsNotNull() {
			addCriterion("jobst is not null");
			return (Criteria) this;
		}

		public Criteria andJobstEqualTo(Date value) {
			addCriterionForJDBCDate("jobst =", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstNotEqualTo(Date value) {
			addCriterionForJDBCDate("jobst <>", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstGreaterThan(Date value) {
			addCriterionForJDBCDate("jobst >", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jobst >=", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstLessThan(Date value) {
			addCriterionForJDBCDate("jobst <", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jobst <=", value, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstIn(List<Date> values) {
			addCriterionForJDBCDate("jobst in", values, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstNotIn(List<Date> values) {
			addCriterionForJDBCDate("jobst not in", values, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jobst between", value1, value2, "jobst");
			return (Criteria) this;
		}

		public Criteria andJobstNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jobst not between", value1, value2,
					"jobst");
			return (Criteria) this;
		}

		public Criteria andIntotimeIsNull() {
			addCriterion("intotime is null");
			return (Criteria) this;
		}

		public Criteria andIntotimeIsNotNull() {
			addCriterion("intotime is not null");
			return (Criteria) this;
		}

		public Criteria andIntotimeEqualTo(Date value) {
			addCriterionForJDBCDate("intotime =", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("intotime <>", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeGreaterThan(Date value) {
			addCriterionForJDBCDate("intotime >", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("intotime >=", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeLessThan(Date value) {
			addCriterionForJDBCDate("intotime <", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("intotime <=", value, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeIn(List<Date> values) {
			addCriterionForJDBCDate("intotime in", values, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("intotime not in", values, "intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("intotime between", value1, value2,
					"intotime");
			return (Criteria) this;
		}

		public Criteria andIntotimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("intotime not between", value1, value2,
					"intotime");
			return (Criteria) this;
		}

		public Criteria andContractIsNull() {
			addCriterion("contract is null");
			return (Criteria) this;
		}

		public Criteria andContractIsNotNull() {
			addCriterion("contract is not null");
			return (Criteria) this;
		}

		public Criteria andContractEqualTo(String value) {
			addCriterion("contract =", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotEqualTo(String value) {
			addCriterion("contract <>", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractGreaterThan(String value) {
			addCriterion("contract >", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractGreaterThanOrEqualTo(String value) {
			addCriterion("contract >=", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLessThan(String value) {
			addCriterion("contract <", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLessThanOrEqualTo(String value) {
			addCriterion("contract <=", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLike(String value) {
			addCriterion("contract like", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotLike(String value) {
			addCriterion("contract not like", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractIn(List<String> values) {
			addCriterion("contract in", values, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotIn(List<String> values) {
			addCriterion("contract not in", values, "contract");
			return (Criteria) this;
		}

		public Criteria andContractBetween(String value1, String value2) {
			addCriterion("contract between", value1, value2, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotBetween(String value1, String value2) {
			addCriterion("contract not between", value1, value2, "contract");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table emp
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table emp
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 02 21:30:59 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}