package com.gm.osoa.orm.mybatis.model;

public class Er {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er.er_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String erId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er.emp_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String empId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er.er_id
     *
     * @return the value of er.er_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getErId() {
        return erId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er.er_id
     *
     * @param erId the value for er.er_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setErId(String erId) {
        this.erId = erId == null ? null : erId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er.roleid
     *
     * @return the value of er.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er.roleid
     *
     * @param roleid the value for er.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er.emp_id
     *
     * @return the value of er.emp_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er.emp_id
     *
     * @param empId the value for er.emp_id
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }
}