package com.gm.osoa.orm.mybatis.model;

public class Privilege {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.pri_id
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String priId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.pri_code
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String priCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.pri_name
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String priName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.pri_url
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String priUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.morf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private Integer morf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.sortno
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String sortno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.is_leaf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private Boolean isLeaf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.bar_icon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String barIcon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.icon_cls
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String iconCls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.micon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String micon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.pid
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.ww
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private Integer ww;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.wh
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	private Integer wh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.pri_id
	 * @return  the value of privilege.pri_id
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getPriId() {
		return priId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.pri_id
	 * @param priId  the value for privilege.pri_id
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setPriId(String priId) {
		this.priId = priId == null ? null : priId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.pri_code
	 * @return  the value of privilege.pri_code
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getPriCode() {
		return priCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.pri_code
	 * @param priCode  the value for privilege.pri_code
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setPriCode(String priCode) {
		this.priCode = priCode == null ? null : priCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.pri_name
	 * @return  the value of privilege.pri_name
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getPriName() {
		return priName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.pri_name
	 * @param priName  the value for privilege.pri_name
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setPriName(String priName) {
		this.priName = priName == null ? null : priName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.pri_url
	 * @return  the value of privilege.pri_url
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getPriUrl() {
		return priUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.pri_url
	 * @param priUrl  the value for privilege.pri_url
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setPriUrl(String priUrl) {
		this.priUrl = priUrl == null ? null : priUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.morf
	 * @return  the value of privilege.morf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Integer getMorf() {
		return morf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.morf
	 * @param morf  the value for privilege.morf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setMorf(Integer morf) {
		this.morf = morf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.sortno
	 * @return  the value of privilege.sortno
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getSortno() {
		return sortno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.sortno
	 * @param sortno  the value for privilege.sortno
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setSortno(String sortno) {
		this.sortno = sortno == null ? null : sortno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.is_leaf
	 * @return  the value of privilege.is_leaf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Boolean getIsLeaf() {
		return isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.is_leaf
	 * @param isLeaf  the value for privilege.is_leaf
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setIsLeaf(Boolean isLeaf) {
		this.isLeaf = isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.bar_icon
	 * @return  the value of privilege.bar_icon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getBarIcon() {
		return barIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.bar_icon
	 * @param barIcon  the value for privilege.bar_icon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setBarIcon(String barIcon) {
		this.barIcon = barIcon == null ? null : barIcon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.icon_cls
	 * @return  the value of privilege.icon_cls
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getIconCls() {
		return iconCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.icon_cls
	 * @param iconCls  the value for privilege.icon_cls
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setIconCls(String iconCls) {
		this.iconCls = iconCls == null ? null : iconCls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.micon
	 * @return  the value of privilege.micon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getMicon() {
		return micon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.micon
	 * @param micon  the value for privilege.micon
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setMicon(String micon) {
		this.micon = micon == null ? null : micon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.pid
	 * @return  the value of privilege.pid
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.pid
	 * @param pid  the value for privilege.pid
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setPid(String pid) {
		this.pid = pid == null ? null : pid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.ww
	 * @return  the value of privilege.ww
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Integer getWw() {
		return ww;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.ww
	 * @param ww  the value for privilege.ww
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setWw(Integer ww) {
		this.ww = ww;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.wh
	 * @return  the value of privilege.wh
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Integer getWh() {
		return wh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.wh
	 * @param wh  the value for privilege.wh
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setWh(Integer wh) {
		this.wh = wh;
	}
}