package com.gm.osoa.orm.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class PrivilegeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public PrivilegeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPriIdIsNull() {
			addCriterion("pri_id is null");
			return (Criteria) this;
		}

		public Criteria andPriIdIsNotNull() {
			addCriterion("pri_id is not null");
			return (Criteria) this;
		}

		public Criteria andPriIdEqualTo(String value) {
			addCriterion("pri_id =", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdNotEqualTo(String value) {
			addCriterion("pri_id <>", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdGreaterThan(String value) {
			addCriterion("pri_id >", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdGreaterThanOrEqualTo(String value) {
			addCriterion("pri_id >=", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdLessThan(String value) {
			addCriterion("pri_id <", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdLessThanOrEqualTo(String value) {
			addCriterion("pri_id <=", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdLike(String value) {
			addCriterion("pri_id like", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdNotLike(String value) {
			addCriterion("pri_id not like", value, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdIn(List<String> values) {
			addCriterion("pri_id in", values, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdNotIn(List<String> values) {
			addCriterion("pri_id not in", values, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdBetween(String value1, String value2) {
			addCriterion("pri_id between", value1, value2, "priId");
			return (Criteria) this;
		}

		public Criteria andPriIdNotBetween(String value1, String value2) {
			addCriterion("pri_id not between", value1, value2, "priId");
			return (Criteria) this;
		}

		public Criteria andPriCodeIsNull() {
			addCriterion("pri_code is null");
			return (Criteria) this;
		}

		public Criteria andPriCodeIsNotNull() {
			addCriterion("pri_code is not null");
			return (Criteria) this;
		}

		public Criteria andPriCodeEqualTo(String value) {
			addCriterion("pri_code =", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeNotEqualTo(String value) {
			addCriterion("pri_code <>", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeGreaterThan(String value) {
			addCriterion("pri_code >", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeGreaterThanOrEqualTo(String value) {
			addCriterion("pri_code >=", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeLessThan(String value) {
			addCriterion("pri_code <", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeLessThanOrEqualTo(String value) {
			addCriterion("pri_code <=", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeLike(String value) {
			addCriterion("pri_code like", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeNotLike(String value) {
			addCriterion("pri_code not like", value, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeIn(List<String> values) {
			addCriterion("pri_code in", values, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeNotIn(List<String> values) {
			addCriterion("pri_code not in", values, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeBetween(String value1, String value2) {
			addCriterion("pri_code between", value1, value2, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriCodeNotBetween(String value1, String value2) {
			addCriterion("pri_code not between", value1, value2, "priCode");
			return (Criteria) this;
		}

		public Criteria andPriNameIsNull() {
			addCriterion("pri_name is null");
			return (Criteria) this;
		}

		public Criteria andPriNameIsNotNull() {
			addCriterion("pri_name is not null");
			return (Criteria) this;
		}

		public Criteria andPriNameEqualTo(String value) {
			addCriterion("pri_name =", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameNotEqualTo(String value) {
			addCriterion("pri_name <>", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameGreaterThan(String value) {
			addCriterion("pri_name >", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameGreaterThanOrEqualTo(String value) {
			addCriterion("pri_name >=", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameLessThan(String value) {
			addCriterion("pri_name <", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameLessThanOrEqualTo(String value) {
			addCriterion("pri_name <=", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameLike(String value) {
			addCriterion("pri_name like", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameNotLike(String value) {
			addCriterion("pri_name not like", value, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameIn(List<String> values) {
			addCriterion("pri_name in", values, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameNotIn(List<String> values) {
			addCriterion("pri_name not in", values, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameBetween(String value1, String value2) {
			addCriterion("pri_name between", value1, value2, "priName");
			return (Criteria) this;
		}

		public Criteria andPriNameNotBetween(String value1, String value2) {
			addCriterion("pri_name not between", value1, value2, "priName");
			return (Criteria) this;
		}

		public Criteria andPriUrlIsNull() {
			addCriterion("pri_url is null");
			return (Criteria) this;
		}

		public Criteria andPriUrlIsNotNull() {
			addCriterion("pri_url is not null");
			return (Criteria) this;
		}

		public Criteria andPriUrlEqualTo(String value) {
			addCriterion("pri_url =", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlNotEqualTo(String value) {
			addCriterion("pri_url <>", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlGreaterThan(String value) {
			addCriterion("pri_url >", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlGreaterThanOrEqualTo(String value) {
			addCriterion("pri_url >=", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlLessThan(String value) {
			addCriterion("pri_url <", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlLessThanOrEqualTo(String value) {
			addCriterion("pri_url <=", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlLike(String value) {
			addCriterion("pri_url like", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlNotLike(String value) {
			addCriterion("pri_url not like", value, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlIn(List<String> values) {
			addCriterion("pri_url in", values, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlNotIn(List<String> values) {
			addCriterion("pri_url not in", values, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlBetween(String value1, String value2) {
			addCriterion("pri_url between", value1, value2, "priUrl");
			return (Criteria) this;
		}

		public Criteria andPriUrlNotBetween(String value1, String value2) {
			addCriterion("pri_url not between", value1, value2, "priUrl");
			return (Criteria) this;
		}

		public Criteria andMorfIsNull() {
			addCriterion("morf is null");
			return (Criteria) this;
		}

		public Criteria andMorfIsNotNull() {
			addCriterion("morf is not null");
			return (Criteria) this;
		}

		public Criteria andMorfEqualTo(Integer value) {
			addCriterion("morf =", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfNotEqualTo(Integer value) {
			addCriterion("morf <>", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfGreaterThan(Integer value) {
			addCriterion("morf >", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfGreaterThanOrEqualTo(Integer value) {
			addCriterion("morf >=", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfLessThan(Integer value) {
			addCriterion("morf <", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfLessThanOrEqualTo(Integer value) {
			addCriterion("morf <=", value, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfIn(List<Integer> values) {
			addCriterion("morf in", values, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfNotIn(List<Integer> values) {
			addCriterion("morf not in", values, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfBetween(Integer value1, Integer value2) {
			addCriterion("morf between", value1, value2, "morf");
			return (Criteria) this;
		}

		public Criteria andMorfNotBetween(Integer value1, Integer value2) {
			addCriterion("morf not between", value1, value2, "morf");
			return (Criteria) this;
		}

		public Criteria andSortnoIsNull() {
			addCriterion("sortno is null");
			return (Criteria) this;
		}

		public Criteria andSortnoIsNotNull() {
			addCriterion("sortno is not null");
			return (Criteria) this;
		}

		public Criteria andSortnoEqualTo(String value) {
			addCriterion("sortno =", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotEqualTo(String value) {
			addCriterion("sortno <>", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoGreaterThan(String value) {
			addCriterion("sortno >", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoGreaterThanOrEqualTo(String value) {
			addCriterion("sortno >=", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoLessThan(String value) {
			addCriterion("sortno <", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoLessThanOrEqualTo(String value) {
			addCriterion("sortno <=", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoLike(String value) {
			addCriterion("sortno like", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotLike(String value) {
			addCriterion("sortno not like", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoIn(List<String> values) {
			addCriterion("sortno in", values, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotIn(List<String> values) {
			addCriterion("sortno not in", values, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoBetween(String value1, String value2) {
			addCriterion("sortno between", value1, value2, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotBetween(String value1, String value2) {
			addCriterion("sortno not between", value1, value2, "sortno");
			return (Criteria) this;
		}

		public Criteria andIsLeafIsNull() {
			addCriterion("is_leaf is null");
			return (Criteria) this;
		}

		public Criteria andIsLeafIsNotNull() {
			addCriterion("is_leaf is not null");
			return (Criteria) this;
		}

		public Criteria andIsLeafEqualTo(Boolean value) {
			addCriterion("is_leaf =", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafNotEqualTo(Boolean value) {
			addCriterion("is_leaf <>", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafGreaterThan(Boolean value) {
			addCriterion("is_leaf >", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_leaf >=", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafLessThan(Boolean value) {
			addCriterion("is_leaf <", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafLessThanOrEqualTo(Boolean value) {
			addCriterion("is_leaf <=", value, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafIn(List<Boolean> values) {
			addCriterion("is_leaf in", values, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafNotIn(List<Boolean> values) {
			addCriterion("is_leaf not in", values, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafBetween(Boolean value1, Boolean value2) {
			addCriterion("is_leaf between", value1, value2, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andIsLeafNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_leaf not between", value1, value2, "isLeaf");
			return (Criteria) this;
		}

		public Criteria andBarIconIsNull() {
			addCriterion("bar_icon is null");
			return (Criteria) this;
		}

		public Criteria andBarIconIsNotNull() {
			addCriterion("bar_icon is not null");
			return (Criteria) this;
		}

		public Criteria andBarIconEqualTo(String value) {
			addCriterion("bar_icon =", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconNotEqualTo(String value) {
			addCriterion("bar_icon <>", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconGreaterThan(String value) {
			addCriterion("bar_icon >", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconGreaterThanOrEqualTo(String value) {
			addCriterion("bar_icon >=", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconLessThan(String value) {
			addCriterion("bar_icon <", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconLessThanOrEqualTo(String value) {
			addCriterion("bar_icon <=", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconLike(String value) {
			addCriterion("bar_icon like", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconNotLike(String value) {
			addCriterion("bar_icon not like", value, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconIn(List<String> values) {
			addCriterion("bar_icon in", values, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconNotIn(List<String> values) {
			addCriterion("bar_icon not in", values, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconBetween(String value1, String value2) {
			addCriterion("bar_icon between", value1, value2, "barIcon");
			return (Criteria) this;
		}

		public Criteria andBarIconNotBetween(String value1, String value2) {
			addCriterion("bar_icon not between", value1, value2, "barIcon");
			return (Criteria) this;
		}

		public Criteria andIconClsIsNull() {
			addCriterion("icon_cls is null");
			return (Criteria) this;
		}

		public Criteria andIconClsIsNotNull() {
			addCriterion("icon_cls is not null");
			return (Criteria) this;
		}

		public Criteria andIconClsEqualTo(String value) {
			addCriterion("icon_cls =", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsNotEqualTo(String value) {
			addCriterion("icon_cls <>", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsGreaterThan(String value) {
			addCriterion("icon_cls >", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsGreaterThanOrEqualTo(String value) {
			addCriterion("icon_cls >=", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsLessThan(String value) {
			addCriterion("icon_cls <", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsLessThanOrEqualTo(String value) {
			addCriterion("icon_cls <=", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsLike(String value) {
			addCriterion("icon_cls like", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsNotLike(String value) {
			addCriterion("icon_cls not like", value, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsIn(List<String> values) {
			addCriterion("icon_cls in", values, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsNotIn(List<String> values) {
			addCriterion("icon_cls not in", values, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsBetween(String value1, String value2) {
			addCriterion("icon_cls between", value1, value2, "iconCls");
			return (Criteria) this;
		}

		public Criteria andIconClsNotBetween(String value1, String value2) {
			addCriterion("icon_cls not between", value1, value2, "iconCls");
			return (Criteria) this;
		}

		public Criteria andMiconIsNull() {
			addCriterion("micon is null");
			return (Criteria) this;
		}

		public Criteria andMiconIsNotNull() {
			addCriterion("micon is not null");
			return (Criteria) this;
		}

		public Criteria andMiconEqualTo(String value) {
			addCriterion("micon =", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconNotEqualTo(String value) {
			addCriterion("micon <>", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconGreaterThan(String value) {
			addCriterion("micon >", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconGreaterThanOrEqualTo(String value) {
			addCriterion("micon >=", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconLessThan(String value) {
			addCriterion("micon <", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconLessThanOrEqualTo(String value) {
			addCriterion("micon <=", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconLike(String value) {
			addCriterion("micon like", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconNotLike(String value) {
			addCriterion("micon not like", value, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconIn(List<String> values) {
			addCriterion("micon in", values, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconNotIn(List<String> values) {
			addCriterion("micon not in", values, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconBetween(String value1, String value2) {
			addCriterion("micon between", value1, value2, "micon");
			return (Criteria) this;
		}

		public Criteria andMiconNotBetween(String value1, String value2) {
			addCriterion("micon not between", value1, value2, "micon");
			return (Criteria) this;
		}

		public Criteria andPidIsNull() {
			addCriterion("pid is null");
			return (Criteria) this;
		}

		public Criteria andPidIsNotNull() {
			addCriterion("pid is not null");
			return (Criteria) this;
		}

		public Criteria andPidEqualTo(String value) {
			addCriterion("pid =", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotEqualTo(String value) {
			addCriterion("pid <>", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThan(String value) {
			addCriterion("pid >", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidGreaterThanOrEqualTo(String value) {
			addCriterion("pid >=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThan(String value) {
			addCriterion("pid <", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLessThanOrEqualTo(String value) {
			addCriterion("pid <=", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidLike(String value) {
			addCriterion("pid like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotLike(String value) {
			addCriterion("pid not like", value, "pid");
			return (Criteria) this;
		}

		public Criteria andPidIn(List<String> values) {
			addCriterion("pid in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotIn(List<String> values) {
			addCriterion("pid not in", values, "pid");
			return (Criteria) this;
		}

		public Criteria andPidBetween(String value1, String value2) {
			addCriterion("pid between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andPidNotBetween(String value1, String value2) {
			addCriterion("pid not between", value1, value2, "pid");
			return (Criteria) this;
		}

		public Criteria andWwIsNull() {
			addCriterion("ww is null");
			return (Criteria) this;
		}

		public Criteria andWwIsNotNull() {
			addCriterion("ww is not null");
			return (Criteria) this;
		}

		public Criteria andWwEqualTo(Integer value) {
			addCriterion("ww =", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwNotEqualTo(Integer value) {
			addCriterion("ww <>", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwGreaterThan(Integer value) {
			addCriterion("ww >", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwGreaterThanOrEqualTo(Integer value) {
			addCriterion("ww >=", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwLessThan(Integer value) {
			addCriterion("ww <", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwLessThanOrEqualTo(Integer value) {
			addCriterion("ww <=", value, "ww");
			return (Criteria) this;
		}

		public Criteria andWwIn(List<Integer> values) {
			addCriterion("ww in", values, "ww");
			return (Criteria) this;
		}

		public Criteria andWwNotIn(List<Integer> values) {
			addCriterion("ww not in", values, "ww");
			return (Criteria) this;
		}

		public Criteria andWwBetween(Integer value1, Integer value2) {
			addCriterion("ww between", value1, value2, "ww");
			return (Criteria) this;
		}

		public Criteria andWwNotBetween(Integer value1, Integer value2) {
			addCriterion("ww not between", value1, value2, "ww");
			return (Criteria) this;
		}

		public Criteria andWhIsNull() {
			addCriterion("wh is null");
			return (Criteria) this;
		}

		public Criteria andWhIsNotNull() {
			addCriterion("wh is not null");
			return (Criteria) this;
		}

		public Criteria andWhEqualTo(Integer value) {
			addCriterion("wh =", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhNotEqualTo(Integer value) {
			addCriterion("wh <>", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhGreaterThan(Integer value) {
			addCriterion("wh >", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhGreaterThanOrEqualTo(Integer value) {
			addCriterion("wh >=", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhLessThan(Integer value) {
			addCriterion("wh <", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhLessThanOrEqualTo(Integer value) {
			addCriterion("wh <=", value, "wh");
			return (Criteria) this;
		}

		public Criteria andWhIn(List<Integer> values) {
			addCriterion("wh in", values, "wh");
			return (Criteria) this;
		}

		public Criteria andWhNotIn(List<Integer> values) {
			addCriterion("wh not in", values, "wh");
			return (Criteria) this;
		}

		public Criteria andWhBetween(Integer value1, Integer value2) {
			addCriterion("wh between", value1, value2, "wh");
			return (Criteria) this;
		}

		public Criteria andWhNotBetween(Integer value1, Integer value2) {
			addCriterion("wh not between", value1, value2, "wh");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table privilege
	 * @mbggenerated  Sun Sep 29 14:12:03 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table privilege
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 29 10:48:09 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}