package com.gm.osoa.orm.mybatis.model;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.springframework.format.annotation.DateTimeFormat;

import com.gm.osoa.common.JsonDateSerializer;

public class Roles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_name
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.cdate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date cdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.udate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date udate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.remark
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.roleid
     *
     * @return the value of roles.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.roleid
     *
     * @param roleid the value for roles.roleid
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_name
     *
     * @return the value of roles.role_name
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_name
     *
     * @param roleName the value for roles.role_name
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.cdate
     *
     * @return the value of roles.cdate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    @JsonSerialize(using = JsonDateSerializer.class)
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.cdate
     *
     * @param cdate the value for roles.cdate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.udate
     *
     * @return the value of roles.udate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    @JsonSerialize(using = JsonDateSerializer.class)
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.udate
     *
     * @param udate the value for roles.udate
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.remark
     *
     * @return the value of roles.remark
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.remark
     *
     * @param remark the value for roles.remark
     *
     * @mbggenerated Sun Sep 29 10:48:09 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}