package com.gm.osoa.orm.mybatis.model;

public class SysTp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tp.tp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String tpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tp.tp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String tpCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tp.tp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String tpName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tp.tp_type
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String tpType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tp.tp_id
	 * @return  the value of sys_tp.tp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getTpId() {
		return tpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tp.tp_id
	 * @param tpId  the value for sys_tp.tp_id
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setTpId(String tpId) {
		this.tpId = tpId == null ? null : tpId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tp.tp_code
	 * @return  the value of sys_tp.tp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getTpCode() {
		return tpCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tp.tp_code
	 * @param tpCode  the value for sys_tp.tp_code
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setTpCode(String tpCode) {
		this.tpCode = tpCode == null ? null : tpCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tp.tp_name
	 * @return  the value of sys_tp.tp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getTpName() {
		return tpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tp.tp_name
	 * @param tpName  the value for sys_tp.tp_name
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setTpName(String tpName) {
		this.tpName = tpName == null ? null : tpName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tp.tp_type
	 * @return  the value of sys_tp.tp_type
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getTpType() {
		return tpType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tp.tp_type
	 * @param tpType  the value for sys_tp.tp_type
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setTpType(String tpType) {
		this.tpType = tpType == null ? null : tpType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tp.remark
	 * @return  the value of sys_tp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tp.remark
	 * @param remark  the value for sys_tp.remark
	 * @mbggenerated  Tue Sep 03 10:32:39 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}